try perf-analyzer in CI

diff --git a/.github/workflows/ci-github-cms.yaml b/.github/workflows/ci-github-cms.yaml
--- a/.github/workflows/ci-github-cms.yaml
+++ b/.github/workflows/ci-github-cms.yaml
@@ -67,10 +67,16 @@ jobs:
         run: |
           kubectl get all -n cms
 
-      # - name: Run Test CMSSW Workflow
-      #   run: |
-      #     # TODO
-      #     sleep 120
-              
+      - name: Run Perf Analyzer Job
+        run: |
+          kubectl apply -f ci/perf-analyzer-job.yaml
+          kubectl wait --for=condition=complete job/perf-analyzer-job -n cms --timeout=300s || \
+          (echo "Perf-analyzer job did not complete in time or failed." && exit 1)
+
+          POD_NAME=$(kubectl get pods -n cms -l job-name=perf-analyzer-job -o jsonpath="{.items[0].metadata.name}")
+          echo "========== Perf Analyzer Logs =========="
+          kubectl logs -n cms "$POD_NAME"
+          echo "========================================"
+
       - name: Cleanup
         run: kind delete cluster --name gh-k8s-cluster
