fix CI

diff --git a/.github/workflows/ci-github-cms.yaml b/.github/workflows/ci-github-cms.yaml
--- a/.github/workflows/ci-github-cms.yaml
+++ b/.github/workflows/ci-github-cms.yaml
@@ -56,7 +56,7 @@ jobs:
         run: |
           kubectl wait --for condition=Ready pod --all -n cvmfs-csi --timeout 120s
           kubectl wait --for condition=Ready pod -l app.kubernetes.io/component=envoy --timeout 120s -n cms
-          while ! kubectl logs deployment/ci-sonic-triton -n cms --all-containers=true; do
+          while ! kubectl logs deployment/supersonic-triton -n cms --all-containers=true; do
               echo "Waiting for containers to become available..."
               # kubectl describe pods -n cms -l app.kubernetes.io/component=triton
               sleep 10
@@ -71,7 +71,7 @@ jobs:
         run: |
           kubectl apply -f ci/perf-analyzer-job.yaml
           kubectl wait --for=condition=complete job/perf-analyzer-job -n cms --timeout=90s || \
-          (echo "Perf-analyzer job did not complete in time or failed.")
+          (echo "Perf-analyzer job did not complete in time or failed." && exit 1)
 
           POD_NAME=$(kubectl get pods -n cms -l job-name=perf-analyzer-job -o jsonpath="{.items[0].metadata.name}")
           echo "========== Perf Analyzer Logs =========="
