cleanup

diff --git a/.github/workflows/ci-github-cms.yaml b/.github/workflows/ci-github-cms.yaml
--- a/.github/workflows/ci-github-cms.yaml
+++ b/.github/workflows/ci-github-cms.yaml
@@ -65,7 +65,7 @@ jobs:
         run: |
           kubectl apply -f ci/perf-analyzer-job.yaml
           kubectl wait --for=condition=complete job/perf-analyzer-job -n cms --timeout=180s || \
-          (echo "Perf-analyzer job did not complete in time or failed." )
+          (echo "Perf-analyzer job did not complete in time or failed." && exit 1)
 
           POD_NAME=$(kubectl get pods -n cms -l job-name=perf-analyzer-job -o jsonpath="{.items[0].metadata.name}")
           echo "========== Perf Analyzer Logs =========="
